[package]
name = "lc_middlewares"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
tower-http = { workspace = true }
anyhow = { workspace = true }

lc_utils = { workspace = true }
lc_services = { workspace = true }
