[package]
name = "lc_services"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }

lc_utils = { workspace = true }
lc_dto = { workspace = true }
lc_models = { workspace = true }
